// Generated by CoffeeScript 1.10.0
var React;

React = require('preact');

exports.XAxis = function(arg) {
  var border, format, height, label, labels, padding, position, style, ticks, width, x;
  width = arg.width, height = arg.height, x = arg.x, padding = arg.padding, position = arg.position, format = arg.format, ticks = arg.ticks, labels = arg.labels, label = arg.label, border = arg.border;
  padding || (padding = 0);
  style = {
    width: width,
    height: height,
    position: 'absolute',
    left: 0
  };
  if (position === 'bottom') {
    style.bottom = padding;
  } else {
    style.top = padding;
  }
  return React.createElement("svg", {
    "className": 'axis x-axis',
    "style": style,
    "height": height,
    "width": width
  }, (labels != null ? React.createElement("g", {
    "className": 'labels'
  }, Object.keys(labels).map(function(label_x) {
    return React.createElement("text", {
      "x": x(label_x),
      "y": height,
      "textAnchor": 'middle',
      "key": label_x
    }, labels[label_x]);
  })) : x.ticks(ticks || 10).map((function(_this) {
    return function(t, ti) {
      var alignment_baseline, text_y, tick_label;
      tick_label = format != null ? format(t) : t.toFixed(0);
      text_y = position === 'bottom' ? height : 0;
      alignment_baseline = position === 'bottom' ? 'baseline' : 'hanging';
      return React.createElement("text", {
        "x": x(t),
        "y": text_y,
        "textAnchor": 'middle',
        "key": ti,
        "alignmentBaseline": alignment_baseline
      }, tick_label);
    };
  })(this))), (label ? React.createElement("text", {
    "className": 'label',
    "x": width,
    "y": height,
    "key": 'label',
    "style": {
      fontWeight: 'bold'
    }
  }, label) : void 0), (border ? React.createElement("rect", {
    "height": 1,
    "x": height,
    "width": width - height
  }) : void 0));
};

exports.YAxis = function(arg) {
  var border, format, height, label, labels, padding, position, style, ticks, width, y;
  width = arg.width, height = arg.height, y = arg.y, padding = arg.padding, position = arg.position, format = arg.format, ticks = arg.ticks, label = arg.label, labels = arg.labels, border = arg.border;
  padding || (padding = 0);
  style = {
    width: width,
    height: height,
    position: 'absolute',
    top: 0
  };
  if (position === 'left') {
    style.left = padding;
  } else {
    style.right = padding;
  }
  return React.createElement("svg", {
    "className": 'axis y-axis',
    "style": style,
    "height": height,
    "width": width
  }, (labels != null ? React.createElement("g", {
    "className": 'labels',
    "transform": "translate(-20,0)"
  }, Object.keys(labels).map(function(label_y) {
    return React.createElement("text", {
      "y": y(label_y),
      "x": 0,
      "textAnchor": 'middle',
      "key": label_y
    }, labels[label_y]);
  })) : y.ticks(ticks || (height / 20)).map(function(t, ti) {
    var text_anchor, text_x, tick_label;
    tick_label = format != null ? format(t) : t.toFixed(0);
    text_x = position === 'left' ? 0 : width;
    text_anchor = position === 'left' ? 'start' : 'end';
    return React.createElement("text", {
      "y": y(t),
      "x": text_x,
      "textAnchor": text_anchor,
      "alignmentBaseline": 'middle',
      "key": ti
    }, tick_label);
  })), (label != null ? React.createElement("text", {
    "className": 'label',
    "y": 0,
    "textAnchor": 'start',
    "key": 'label',
    "style": {
      fontWeight: 'bold'
    }
  }, label) : void 0), (border ? React.createElement("rect", {
    "width": width,
    "x": 0,
    "y": 0,
    "height": height
  }) : void 0));
};
