// Generated by CoffeeScript 1.10.0
var BarChart, Chart, React, d3, helpers;

React = require('react');

d3 = require('d3');

helpers = require('./helpers');

Chart = require('./chart');

module.exports = BarChart = React.createClass({displayName: "BarChart",
  mixins: [Chart],
  xDomain: function() {
    var x_extent;
    x_extent = d3.extent(this.props.data, function(d) {
      return d.x;
    });
    x_extent[1] += 1;
    return x_extent;
  },
  renderChart: function() {
    var adjust, bar_gap, bar_width, color, data, height, onClick, padding, ref, ref1, width, x, y;
    ref = this.props, width = ref.width, height = ref.height, padding = ref.padding, data = ref.data, bar_width = ref.bar_width, adjust = ref.adjust, color = ref.color, onClick = ref.onClick;
    ref1 = this.state, x = ref1.x, y = ref1.y;
    bar_width || (bar_width = width / data.length - 1);
    bar_gap = 0;
    return React.createElement("svg", {
      "className": 'bar-chart',
      "style": {
        width: width,
        height: height,
        position: 'absolute',
        top: 0
      }
    }, data.map((function(_this) {
      return function(d, di) {
        var last_y, this_x, this_y;
        console.log('d', d);
        last_y = y(d.y0 || y.domain()[0]);
        this_y = y(d.y1 || d.y);
        this_x = x(d.x);
        return React.createElement("rect", {
          "onClick": onClick != null ? onClick.bind(null, d) : void 0,
          "key": di,
          "x": this_x,
          "y": this_y,
          "width": bar_width,
          "height": last_y - this_y,
          "fill": helpers.interpretColor(color)
        });
      };
    })(this)));
  }
});
