// Generated by CoffeeScript 1.8.0
module.exports = function(ds, n_bins) {
  var bin_count, bin_i, d, data, dt, x0, x1, _i, _j, _len;
  if (n_bins == null) {
    n_bins = 20;
  }
  data = [];
  ds.sort(function(a, b) {
    return a.x - b.x;
  });
  x0 = ds[0].x;
  x1 = ds.slice(-1)[0].x;
  dt = (x1 - x0) / n_bins;
  bin_i = 0;
  bin_count = 0;
  for (bin_i = _i = 0; 0 <= n_bins ? _i < n_bins : _i > n_bins; bin_i = 0 <= n_bins ? ++_i : --_i) {
    for (_j = 0, _len = ds.length; _j < _len; _j++) {
      d = ds[_j];
      if (d.x > x0 + dt * (bin_i + 1)) {
        break;
      } else {
        bin_count += d.y || 1;
      }
    }
    data.push({
      x: bin_i,
      y: bin_count
    });
    ds = ds.slice(bin_count);
    bin_count = 0;
  }
  return data;
};
