// Generated by CoffeeScript 1.12.7
module.exports = function(ds, n_bins) {
  var bin_count, bin_i, d, data, dt, i, j, len, ref, x0, x1;
  if (n_bins == null) {
    n_bins = 20;
  }
  data = [];
  ds.sort(function(a, b) {
    return a.x - b.x;
  });
  x0 = ds[0].x;
  x1 = ds.slice(-1)[0].x;
  dt = (x1 - x0) / n_bins;
  bin_i = 0;
  bin_count = 0;
  for (bin_i = i = 0, ref = n_bins; 0 <= ref ? i < ref : i > ref; bin_i = 0 <= ref ? ++i : --i) {
    for (j = 0, len = ds.length; j < len; j++) {
      d = ds[j];
      if (d.x > x0 + dt * (bin_i + 1)) {
        break;
      } else {
        bin_count += d.y || 1;
      }
    }
    data.push({
      x: bin_i,
      y: bin_count
    });
    ds = ds.slice(bin_count);
    bin_count = 0;
  }
  return data;
};
