// Generated by CoffeeScript 1.8.0
var Chart, React, XAxis, YAxis, d3, flatten, helpers, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

React = require('react');

d3 = require('d3');

_ref = require('./axes'), XAxis = _ref.XAxis, YAxis = _ref.YAxis;

helpers = require('./helpers');

flatten = function(ls) {
  var flat, i, l, _i, _j, _len, _len1;
  flat = [];
  for (_i = 0, _len = ls.length; _i < _len; _i++) {
    l = ls[_i];
    if (Array.isArray(l)) {
      for (_j = 0, _len1 = l.length; _j < _len1; _j++) {
        i = l[_j];
        flat.push(i);
      }
    }
  }
  return flat;
};

module.exports = Chart = (function(_super) {
  __extends(Chart, _super);

  function Chart() {
    return Chart.__super__.constructor.apply(this, arguments);
  }

  Chart.prototype.getDefaultProps = function() {
    return {
      width: 100,
      height: 100,
      padding: 0,
      axis_size: 20,
      color: d3.scaleOrdinal(d3.schemeCategory10)
    };
  };

  Chart.prototype.componentWillMount = function() {
    return this.createAxes(this.props);
  };

  Chart.prototype.componentWillReceiveProps = function(next_props) {
    return this.createAxes(next_props);
  };

  Chart.prototype.shouldComponentUpdate = function(next_props, next_state) {
    var _ref1;
    if (Array.isArray((_ref1 = next_props.data) != null ? _ref1[0] : void 0)) {
      return true;
    }
    if (next_props.data.length !== this.props.data.length) {
      return true;
    } else if ((next_props.width !== this.props.width) || (next_props.height !== this.props.height)) {
      return true;
    } else if ((next_props.y !== this.props.y) || (next_props.x !== this.props.x)) {
      return true;
    } else if (this.props.checkForUpdate) {
      return this.props.checkForUpdate(this.props, next_props, next_state);
    } else {
      return false;
    }
  };

  Chart.prototype.createAxes = function(props) {
    var data, flat_data, height, i, padding, width, x, x_axis, x_extent, y, y_axis, y_extent, _data, _i, _j, _len, _len1, _ref1;
    x = props.x, y = props.y, width = props.width, height = props.height, data = props.data, padding = props.padding, x_axis = props.x_axis, y_axis = props.y_axis;
    padding = helpers.transformPadding(padding);
    if (this.multi) {
      flat_data = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        _data = data[_i];
        for (_j = 0, _len1 = _data.length; _j < _len1; _j++) {
          i = _data[_j];
          flat_data.push(i);
        }
      }
    } else {
      flat_data = data;
    }
    if (x == null) {
      x_extent = (x_axis != null ? x_axis.domain : void 0) || (typeof this.xDomain === "function" ? this.xDomain() : void 0) || d3.extent(flat_data, function(d) {
        return d.x;
      });
      x = d3.scaleLinear().range([padding.left, width - padding.right]).domain(x_extent);
    }
    if (y == null) {
      y_extent = (y_axis != null ? y_axis.domain : void 0) || d3.extent(flat_data, function(d) {
        return d.y;
      });
      if (y_axis != null ? y_axis.zero : void 0) {
        y_extent = [
          0, (y_axis != null ? (_ref1 = y_axis.domain) != null ? _ref1[1] : void 0 : void 0) || d3.max(flat_data, function(d) {
            return d.y;
          })
        ];
      }
      y = d3.scaleLinear().range([height - padding.bottom, padding.top]).domain(y_extent);
    }
    return this.setState({
      x: x,
      y: y
    });
  };

  Chart.prototype.calculateHeight = function() {
    if (this.chartHeight != null) {
      return this.chartHeight();
    } else {
      return this.props.height;
    }
  };

  Chart.prototype.render = function() {
    var axis_size, color, container_height, data, follower, height, padding, title, width, x_axis, y_axis, _ref1;
    _ref1 = this.props, width = _ref1.width, height = _ref1.height, data = _ref1.data, title = _ref1.title, color = _ref1.color, padding = _ref1.padding, axis_size = _ref1.axis_size, follower = _ref1.follower, x_axis = _ref1.x_axis, y_axis = _ref1.y_axis;
    padding = helpers.transformPadding(padding);
    x_axis || (x_axis = {});
    y_axis || (y_axis = {});
    axis_size || (axis_size = 1);
    container_height = this.calculateHeight();
    return React.createElement("div", {
      "className": 'chart',
      "style": {
        position: 'relative',
        width: width,
        height: container_height
      },
      "height": container_height,
      "width": width
    }, (title ? React.createElement("div", {
      "className": 'title'
    }, title) : void 0), this.renderChart(), (!x_axis.hidden ? React.createElement(XAxis, React.__spread({
      "x": this.state.x,
      "axis_size": axis_size,
      "width": width,
      "height": this.props.height,
      "position": 'bottom'
    }, x_axis)) : void 0), (!y_axis.hidden ? React.createElement(YAxis, React.__spread({
      "y": this.state.y,
      "axis_size": axis_size,
      "height": this.props.height,
      "width": axis_size,
      "position": 'left'
    }, y_axis)) : void 0));
  };

  return Chart;

})(React.Component);
