// Generated by CoffeeScript 1.8.0
var Follower, React, d3, helpers, r,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

React = require('react');

d3 = require('d3');

helpers = require('./helpers');

r = 5;

module.exports = Follower = (function(_super) {
  __extends(Follower, _super);

  function Follower(props) {
    this.state = {
      mouseX: props.width / 2,
      mouseY: props.height / 2
    };
  }

  Follower.prototype.onMouseMove = function(e) {
    var bounds, mouseX, mouseY;
    bounds = this.refs.container.getBoundingClientRect();
    mouseX = e.clientX - bounds.left;
    mouseY = e.clientY - bounds.top;
    return this.setState({
      mouseX: mouseX,
      mouseY: mouseY
    });
  };

  Follower.prototype.render = function() {
    var color, data, format, height, mouseX, mouseY, multi, width, x, xx, y, _ref, _ref1;
    _ref = this.props, width = _ref.width, height = _ref.height, data = _ref.data, x = _ref.x, y = _ref.y, color = _ref.color, mouseX = _ref.mouseX, mouseY = _ref.mouseY, format = _ref.format, multi = _ref.multi;
    _ref1 = this.state, mouseX = _ref1.mouseX, mouseY = _ref1.mouseY;
    xx = x.invert(mouseX);
    if (!multi) {
      data = [data];
    }
    return React.createElement("svg", {
      "className": 'follower-container',
      "ref": 'container',
      "style": {
        width: width,
        height: height,
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0
      },
      "onMouseMove": this.onMouseMove.bind(this)
    }, React.createElement("rect", {
      "className": 'follower-line follower-vertical',
      "style": {
        width: 1,
        height: height,
        y: 0,
        x: mouseX
      }
    }), React.createElement("rect", {
      "className": 'follower-line follower-horizontal',
      "style": {
        width: width,
        height: 1,
        y: mouseY,
        x: 0
      }
    }), data.map(function(data, di) {
      var d, follower, value, yy, _i, _len;
      follower = {};
      yy = 0;
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        d = data[_i];
        if (d.x > xx) {
          yy = d.y;
          break;
        }
      }
      value = yy;
      if (yy === 0) {
        return React.createElement("div", {
          "key": di
        });
      }
      return React.createElement("g", {
        "className": 'follower',
        "transform": "translate(" + mouseX + ", " + (y(yy)) + ")",
        "key": di
      }, React.createElement("circle", {
        "className": 'follower-dot',
        "r": r,
        "style": {
          fill: helpers.interpretColor(color, data)
        }
      }), React.createElement("text", {
        "className": 'follower-label',
        "y": 0.,
        "x": r + 5,
        "alignmentBaseline": 'middle'
      }, (format != null ? format(value) : value.toFixed(4))));
    }));
  };

  return Follower;

})(React.Component);
