// Generated by CoffeeScript 1.10.0
var Follower, React, d3, helpers, r;

React = require('react');

d3 = require('d3');

helpers = require('./helpers');

r = 5;

module.exports = Follower = function(arg) {
  var color, data, format, height, mouseX, mouseY, multi, width, x, xx, y;
  width = arg.width, height = arg.height, data = arg.data, x = arg.x, y = arg.y, color = arg.color, mouseX = arg.mouseX, mouseY = arg.mouseY, format = arg.format, multi = arg.multi;
  xx = x.invert(mouseX);
  if (!multi) {
    data = [data];
  }
  return React.createElement("svg", {
    "className": 'follower-container',
    "style": {
      width: width,
      height: height,
      position: 'absolute',
      top: 0,
      left: 0
    }
  }, React.createElement("rect", {
    "className": 'follower-line follower-vertical',
    "style": {
      width: 1,
      height: height,
      y: 0,
      x: mouseX
    }
  }), React.createElement("rect", {
    "className": 'follower-line follower-horizontal',
    "style": {
      width: width,
      height: 1,
      y: mouseY,
      x: 0
    }
  }), data.map(function(data, di) {
    var d, follower, i, len, value, yy;
    follower = {};
    yy = 0;
    for (i = 0, len = data.length; i < len; i++) {
      d = data[i];
      if (d.x > xx) {
        yy = d.y;
        break;
      }
    }
    value = yy;
    if (yy === 0) {
      return React.createElement("div", {
        "key": di
      });
    }
    return React.createElement("g", {
      "className": 'follower',
      "transform": "translate(" + mouseX + ", " + (y(yy)) + ")",
      "key": di
    }, React.createElement("circle", {
      "className": 'follower-dot',
      "r": r,
      "style": {
        fill: helpers.interpretColor(color, di)
      }
    }), React.createElement("text", {
      "className": 'follower-label',
      "y": 0.,
      "x": r + 5,
      "alignmentBaseline": 'middle'
    }, (format != null ? format(value) : value.toFixed(4))));
  }));
};
