// Generated by CoffeeScript 1.10.0
var Gauge, React, color, d3;

React = require('react');

d3 = require('d3');

color = d3.scaleOrdinal(d3.schemeCategory20);

Gauge = React.createClass({displayName: "Gauge",
  angleFromValue: function(val) {
    var angle, full_arc;
    full_arc = (this.end_angle - this.start_angle) || Math.PI * 2;
    return angle = (full_arc * (val - this.min) / (this.max - this.min)) + this.start_angle;
  },
  renderGuide: function() {
    var arc, arc_params, d, end_angle, radius, start_angle, thickness;
    radius = this.radius, thickness = this.thickness, start_angle = this.start_angle, end_angle = this.end_angle;
    arc = d3.arc().innerRadius(radius - Math.floor(thickness / 2) - 2).startAngle(start_angle).endAngle(end_angle).outerRadius(radius - Math.ceil(thickness / 2) + 2).padRadius(2).cornerRadius(2)(arc_params);
    arc_params = {
      startAngle: 0,
      endAngle: Math.PI * 2,
      value: 100,
      data: 100
    };
    d = arc;
    return React.createElement("g", {
      "key": 'guide',
      "className": 'guide'
    }, React.createElement("path", {
      "onClick": (function() {}),
      "key": 'guide-path',
      "x": radius,
      "y": radius,
      "d": d,
      "fill": "#ccc"
    }));
  },
  render: function() {
    var a_color, arc, bar, d, di, end_angle, guide, height, label_d_y, label_padding, markers, max, min, options, radius, ref, ref1, ref2, renderMarker, show_value, start_angle, thickness, title, value, value_color, value_data, value_range, width;
    ref = this.props, width = ref.width, height = ref.height, title = ref.title, value = ref.value, options = ref.options, title = ref.title;
    min = options.min, max = options.max, start_angle = options.start_angle, end_angle = options.end_angle, guide = options.guide, bar = options.bar;
    ref1 = this.props, width = ref1.width, height = ref1.height, options = ref1.options;
    min = options.min, max = options.max, start_angle = options.start_angle, end_angle = options.end_angle, show_value = options.show_value, guide = options.guide, bar = options.bar, label_padding = options.label_padding;
    this.min || (this.min = 0);
    this.max || (this.max = 100);
    this.show_value || (this.show_value = false);
    this.thickness = thickness = (bar != null ? bar.thickness : void 0) || 25;
    this.guide_thickness = (guide != null ? guide.thickness : void 0) || 4;
    label_padding || (label_padding = 0);
    this.radius = radius = (Math.min(width, height) / 2) - label_padding;
    this.start_angle = start_angle || (start_angle = 0);
    this.end_angle = end_angle || (end_angle = Math.PI * 2);
    this.label_d_y = label_d_y = this.props.options.label_d_y || 5;
    markers = this.props.data.filter(function(d) {
      return d.type === 'marker';
    });
    renderMarker = (function(_this) {
      return function(marker, i) {
        var angle, arc, arc_params, d, label_x, label_y, ref2;
        arc = d3.arc().innerRadius(radius - thickness).outerRadius(radius).padRadius(2).cornerRadius(2);
        angle = _this.angleFromValue(marker.value);
        arc_params = {
          startAngle: angle - 0.1,
          endAngle: angle + 0.1,
          value: marker.value,
          data: marker.value
        };
        d = arc.innerRadius(radius - (thickness + 2)).outerRadius(radius + 2)(arc_params);
        ref2 = arc.outerRadius(radius + 75).centroid(arc_params), label_x = ref2[0], label_y = ref2[1];
        return React.createElement("g", {
          "key": i
        }, React.createElement("path", {
          "onClick": (function() {}),
          "key": i,
          "x": radius,
          "y": radius,
          "d": d,
          "fill": "#888"
        }), (marker.label ? React.createElement("text", {
          "className": 'marker-label',
          "x": label_x - 35,
          "y": label_y,
          "key": 'label',
          "style": {
            fontWeight: 'bold'
          }
        }, marker.label + ' - ' + marker.value) : void 0));
      };
    })(this);
    value_data = this.props.data.filter(function(d) {
      return d.type === 'value';
    })[0];
    value = value_data.value;
    value_color = value_data.color;
    value_range = [value, this.max - value];
    arc = d3.arc().innerRadius(radius - thickness).outerRadius(radius).padRadius(2).cornerRadius(2).startAngle(start_angle);
    return React.createElement("svg", {
      "className": 'gauge-chart',
      "key": 'gauge',
      "style": {
        position: 'relative',
        width: width,
        height: height
      }
    }, React.createElement("g", {
      "key": 'mover',
      "transform": "translate(" + (radius + label_padding) + ", " + (radius + label_padding) + ")"
    }, (!((ref2 = options.guide) != null ? ref2.hidden : void 0) ? this.renderGuide() : void 0), React.createElement("g", {
      "className": 'gauge-bar'
    }, (di = 0, d = arc({
      endAngle: this.angleFromValue(value)
    }), a_color = value_color || color(di), React.createElement("path", {
      "onClick": (function() {}),
      "key": di,
      "x": radius,
      "y": radius,
      "d": d,
      "fill": (di === 1 ? 'none' : a_color)
    }))), (show_value ? React.createElement("text", {
      "className": 'value',
      "x": 0.,
      "y": label_d_y,
      "textAnchor": 'middle'
    }, value) : void 0), ((markers != null ? markers.length : void 0) ? markers.map(renderMarker) : void 0)));
  }
});

module.exports = Gauge;
