// Generated by CoffeeScript 1.8.0
var d3, empty_padding;

d3 = require('d3');

empty_padding = {
  left: 0,
  right: 0,
  top: 0,
  bottom: 0
};

exports.transformPadding = function(padding) {
  if (padding == null) {
    padding = 0;
  }
  if (typeof padding === 'number') {
    padding = {
      left: padding,
      right: padding,
      top: padding,
      bottom: padding
    };
  }
  return padding = Object.assign({}, empty_padding, padding);
};

exports.interpretColor = function(color, value) {
  if (typeof color === 'string') {
    return color;
  } else if ((value != null ? value.color : void 0) != null) {
    return value.color;
  } else if (typeof color === 'function') {
    value = value.id || value._id || value.name || value.key || value;
    return color(value);
  } else {
    return '#999';
  }
};
