// Generated by CoffeeScript 1.10.0
var LabeledBarChart, React, d3;

React = require('react');

d3 = require('d3');

module.exports = LabeledBarChart = React.createClass({displayName: "LabeledBarChart",
  getDefaultProps: function() {
    return {
      color: '#000'
    };
  },
  shouldComponentUpdate: function(next_props, next_state) {
    if (next_props.data.length !== this.props.data.length) {
      return true;
    } else if ((next_props.width !== this.props.width) || (next_props.height !== this.props.height)) {
      return true;
    } else if ((next_props.y !== this.props.y) || (next_props.x !== this.props.x)) {
      return true;
    } else {
      return false;
    }
  },
  render: function() {
    var bar_padding, bar_width, data, height, num_bars, ref, width, x, x_extent, y;
    ref = this.props, width = ref.width, height = ref.height, data = ref.data, x = ref.x, y = ref.y, bar_padding = ref.bar_padding;
    num_bars = data.length;
    bar_padding || (bar_padding = 10);
    x_extent = d3.extent([0, width]);
    bar_width = Math.floor(width / num_bars - 1);
    y || (y = d3.scaleLinear().domain([
      0, d3.max(data, function(d) {
        return d.y;
      })
    ]).range([height, 0]));
    return React.createElement("svg", {
      "className": 'bar-chart',
      "style": {
        width: width,
        height: height
      }
    }, data.map((function(_this) {
      return function(d, di) {
        return React.createElement("rect", {
          "key": di,
          "x": bar_width * di,
          "y": y(d.y),
          "width": bar_width - bar_padding,
          "height": height - y(d.y),
          "fill": d.color || _this.props.color,
          "onClick": typeof onClick !== "undefined" && onClick !== null ? onClick.bind(null, data[di]) : void 0
        });
      };
    })(this)));
  }
});
