// Generated by CoffeeScript 1.10.0
var Chart, LabeledBarChart, React, d3,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

React = require('preact');

d3 = require('d3');

Chart = require('./chart');

module.exports = LabeledBarChart = (function(superClass) {
  extend(LabeledBarChart, superClass);

  function LabeledBarChart() {
    return LabeledBarChart.__super__.constructor.apply(this, arguments);
  }

  LabeledBarChart.prototype.renderChart = function() {
    var axis_size, bar_padding, bar_width, cell_width, chart_height, data, height, horizontal, num_bars, options, ref, width, x, x_extent, y;
    ref = this.props, width = ref.width, height = ref.height, data = ref.data, x = ref.x, y = ref.y, options = ref.options, axis_size = ref.axis_size;
    if (options != null) {
      bar_padding = options.bar_padding, bar_width = options.bar_width, horizontal = options.horizontal;
    }
    num_bars = data.length;
    bar_padding || (bar_padding = 10);
    x_extent = d3.extent([0, width]);
    cell_width = Math.floor(width / num_bars - 1);
    y || (y = d3.scaleLinear().domain([
      0, d3.max(data, function(d) {
        return d.y;
      })
    ]).range([height, 0]));
    chart_height = height + 2 * 25;
    return React.createElement("svg", {
      "className": 'bar-chart',
      "style": {
        width: width,
        height: chart_height,
        position: 'absolute'
      },
      "height": chart_height,
      "width": width
    }, data.map((function(_this) {
      return function(d, di) {
        var ref1;
        return React.createElement("g", {
          "className": 'bar'
        }, (ref1 = d.label) != null ? ref1.split(' ').map(function(l, i_label) {
          var label_width, label_x, label_x_tmp, label_y, label_y_tmp;
          label_width = 6.5 * l.length;
          label_x = cell_width * (di + 0.5) - label_width / 2;
          label_y = height + bar_padding + (15 * (i_label + 1));
          if (horizontal) {
            label_y_tmp = label_y;
            label_x_tmp = label_x;
            label_x = label_y;
            label_y = label_x_tmp;
          }
          return React.createElement("text", {
            "className": 'label',
            "y": label_y,
            "x": label_x,
            "width": cell_width
          }, l);
        }) : void 0, React.createElement("rect", {
          "key": di,
          "x": cell_width * (di + 0.25),
          "y": y(d.y),
          "width": bar_width || (cell_width - bar_padding),
          "height": height - y(d.y),
          "fill": d.color || _this.props.color,
          "onClick": typeof onClick !== "undefined" && onClick !== null ? onClick.bind(null, data[di]) : void 0
        }));
      };
    })(this)));
  };

  return LabeledBarChart;

})(Chart);
