// Generated by CoffeeScript 1.10.0
var Legend, React;

React = require('react');

module.exports = Legend = function(arg) {
  var className, data, ref;
  data = arg.data, className = (ref = arg.className) != null ? ref : '';
  console.log(data);
  return React.createElement("div", {
    "className": "legend  " + className
  }, data.map(function(d, j) {
    return React.createElement("div", {
      "key": j,
      "className": "legend-entry"
    }, React.createElement("div", {
      "className": 'legend-swatch',
      "style": {
        background: d.color
      }
    }), React.createElement("div", {
      "className": 'legend-key'
    }, d.label));
  }));
};
