// Generated by CoffeeScript 1.8.0
var Legend, React;

React = require('preact');

module.exports = Legend = function(_arg) {
  var className, data;
  data = _arg.data, className = _arg.className;
  return React.createElement("div", {
    "className": "legend " + (className || '')
  }, data.map(function(d, j) {
    return React.createElement("div", {
      "key": j,
      "className": "legend-entry",
      "onClick": typeof onClick !== "undefined" && onClick !== null ? onClick.bind(null, data[j]) : void 0
    }, React.createElement("div", {
      "className": 'legend-swatch',
      "style": {
        background: d.color
      }
    }), React.createElement("div", {
      "className": 'legend-key'
    }, d.label));
  }));
};
