// Generated by CoffeeScript 1.10.0
var Legend, React;

React = require('react');

module.exports = Legend = function(arg) {
  var data;
  data = arg.data;
  console.log(data);
  return React.createElement("div", {
    "className": 'legend'
  }, data.map(function(d, j) {
    return React.createElement("div", {
      "key": j,
      "className": 'legend-entry'
    }, React.createElement("div", {
      "className": 'legend-swatch',
      "style": {
        background: d.color
      }
    }), React.createElement("div", {
      "className": 'legend-key'
    }, d.label));
  }));
};
