// Generated by CoffeeScript 1.10.0
var LineChart, React, d3;

React = require('react');

d3 = require('d3');

module.exports = LineChart = React.createClass({displayName: "LineChart",
  getDefaultProps: function() {
    return {
      color: '#000',
      curve: true,
      fill: true
    };
  },
  shouldComponentUpdate: function(next_props, next_state) {
    if (next_props.data.length !== this.props.data.length) {
      return true;
    } else if (next_props.width !== this.props.width || next_props.height !== this.props.height) {
      return true;
    } else {
      return false;
    }
  },
  render: function() {
    var curve, d, da, data, fill, height, line, ref, width, x, y;
    ref = this.props, width = ref.width, height = ref.height, data = ref.data, x = ref.x, y = ref.y, curve = ref.curve, fill = ref.fill;
    x || (x = d3.scaleLinear().domain(d3.extent(data, function(d) {
      return d.x;
    })).range([0, width]));
    y || (y = d3.scaleLinear().domain([
      0, d3.max(data, function(d) {
        return d.y;
      })
    ]).range([height, 0]));
    line = d3.line().curve(curve ? d3.curveMonotoneX : d3.curveLinear).x(function(d) {
      return x(d.x);
    }).y(function(d) {
      return y(d.y);
    });
    d = line(data);
    return React.createElement("svg", {
      "className": 'line-chart',
      "style": {
        width: width,
        height: height
      }
    }, (fill ? (da = line(data), React.createElement("path", {
      "d": da,
      "fill": this.props.color,
      "opacity": 0.2,
      "stroke": 'none'
    })) : void 0), React.createElement("path", {
      "d": d,
      "fill": 'none',
      "stroke": this.props.color,
      "strokeWidth": 2
    }));
  }
});
