// Generated by CoffeeScript 1.8.0
var PieChart, React, d3,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

React = require('preact');

d3 = require('d3');

module.exports = PieChart = (function(_super) {
  __extends(PieChart, _super);

  function PieChart() {
    return PieChart.__super__.constructor.apply(this, arguments);
  }

  PieChart.prototype.render = function() {
    var arc, arcs, color, data, height, hover, inner_radius, onClick, onHover, pie, radius, selected, width, _ref;
    _ref = this.props, width = _ref.width, height = _ref.height, data = _ref.data, onClick = _ref.onClick, onHover = _ref.onHover, selected = _ref.selected, hover = _ref.hover, inner_radius = _ref.inner_radius;
    inner_radius || (inner_radius = 0);
    radius = Math.min(width, height) / 2;
    color = d3.scaleOrdinal(d3.schemeCategory20);
    pie = d3.pie().value(function(d) {
      return d.count;
    }).sort(null);
    if (this.props.start_angle) {
      pie = pie.startAngle(this.props.start_angle);
    }
    if (this.props.end_angle) {
      pie = pie.endAngle(this.props.end_angle);
    }
    arc = d3.arc().outerRadius(radius).innerRadius(inner_radius);
    arcs = pie(data).map(arc);
    return React.createElement("svg", {
      "className": 'pie-chart',
      "style": {
        position: 'relative',
        width: width,
        height: height
      }
    }, React.createElement("g", {
      "transform": "translate(" + radius + ", " + radius + ")"
    }, arcs.map((function(_this) {
      return function(arc, di) {
        var className, d;
        d = data[di];
        className = '';
        if (selected === d.label) {
          className += ' selected';
        } else if (hover === d.label) {
          className += ' hover';
        }
        return React.createElement("path", {
          "className": className,
          "onClick": onClick != null ? onClick.bind(null, d) : void 0,
          "onMouseOver": onHover != null ? onHover.bind(null, d) : void 0,
          "onMouseOut": onHover,
          "key": di,
          "x": radius,
          "y": radius,
          "d": arc,
          "fill": d.color || color(di)
        });
      };
    })(this))));
  };

  return PieChart;

})(React.Component);
