// Generated by CoffeeScript 1.10.0
var Chart, React, ScatterChart, d3, helpers;

React = require('react');

d3 = require('d3');

Chart = require('./chart');

helpers = require('./helpers');

module.exports = ScatterChart = React.createClass({displayName: "ScatterChart",
  mixins: [Chart],
  renderChart: function() {
    var color, data, height, r, ref, ref1, width, x, y;
    ref = this.props, width = ref.width, height = ref.height, data = ref.data, color = ref.color, r = ref.r;
    ref1 = this.state, x = ref1.x, y = ref1.y;
    r || (r = 4);
    return React.createElement("svg", {
      "className": 'scatter-chart',
      "style": {
        width: width,
        height: height,
        position: 'absolute'
      }
    }, data.map((function(_this) {
      return function(d, i) {
        var ref2, ref3, renderPoint;
        if (renderPoint = (ref2 = _this.props) != null ? (ref3 = ref2.options) != null ? ref3.renderPoint : void 0 : void 0) {
          return renderPoint(d, {
            x: x,
            y: y
          }, i);
        } else {
          return React.createElement("circle", {
            "className": 'dot',
            "key": i,
            "r": r,
            "cx": x(d.x),
            "cy": y(d.y),
            "fill": helpers.interpretColor(color, d),
            "onClick": typeof onClick !== "undefined" && onClick !== null ? onClick.bind(null, data[di]) : void 0
          });
        }
      };
    })(this)));
  }
});
