// Generated by CoffeeScript 1.10.0
var Chart, React, ScatterChart, d3, helpers,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

React = require('react');

d3 = require('d3');

Chart = require('./chart');

helpers = require('./helpers');

module.exports = ScatterChart = (function(superClass) {
  extend(ScatterChart, superClass);

  function ScatterChart() {
    return ScatterChart.__super__.constructor.apply(this, arguments);
  }

  ScatterChart.prototype.renderChart = function() {
    var color, data, height, r, ref, ref1, width, x, y;
    ref = this.props, width = ref.width, height = ref.height, data = ref.data, color = ref.color, r = ref.r;
    ref1 = this.state, x = ref1.x, y = ref1.y;
    r || (r = 4);
    return React.createElement("svg", {
      "className": 'scatter-chart',
      "style": {
        width: width,
        height: height,
        position: 'absolute'
      },
      "height": height,
      "width": width
    }, data.map((function(_this) {
      return function(d, i) {
        var ref2, ref3, renderPoint;
        if (renderPoint = (ref2 = _this.props) != null ? (ref3 = ref2.options) != null ? ref3.renderPoint : void 0 : void 0) {
          return renderPoint(d, {
            x: x,
            y: y
          }, i);
        } else {
          return React.createElement("circle", {
            "className": 'dot',
            "key": i,
            "r": r,
            "cx": x(d.x),
            "cy": y(d.y),
            "stroke": helpers.interpretColor(color, d),
            "fill": helpers.interpretColor(color, d),
            "onClick": typeof onClick !== "undefined" && onClick !== null ? onClick.bind(null, data[di]) : void 0
          });
        }
      };
    })(this)));
  };

  return ScatterChart;

})(Chart);
