module.exports = {
    LineChart: require './line'
    MultiLineChart: require './multi-line'
    # PieChart: require './pie'
    PieChart: require './pie-preact'
    ScatterChart: require './scatter'
    BarChart: require './bar'
    Histogram: require './histogram'
    # LabeledBarChart: require './labeled-bar'
    LabeledBarChart: require './labeled-bar-preact'
    # LabeledMultiBarChart: require './labeled-multi-bar'
    LabeledMultiBarChart: require './labeled-multi-bar-preact'
    Gauge: require './gauge'
    Chart: require './chart'
    Legend: require './legend'
    Follower: require './follower'
    axes: require './axes'
    bin: require './bin'
}
